
import time

from naoqi import ALProxy
from naoqi import ALBroker
from naoqi import ALModule

# A global counter of the number of loops
count = 10
period = 500
PC_IP = "127.0.0.1"  # Replace this with your computer's IP address
NAO_IP = "172.18.8.98" # Replace this with your NAOqi's IP address
PORT = 9559

# The name of the event generated by ALVisionRecognition
event_name = "PictureDetected"

# The name of our local python module
module_name = "python_module"

class myModule(ALModule):
 """python class myModule test auto documentation"""

def dataChanged(self, strVarName, value, strMessage):
    """callback when data change"""

    print "datachanged", strVarName, " ", value, " ", strMessage
    global count
    count = count - 1

# Create a local broker, connected to the remote naoqi
#broker = ALBroker("pythonBroker", PC_IP, 9999, NAO_IP, 9559)
broker = ALBroker("myBroker",
                            "0.0.0.0",  # listen to anyone
                            0,  # find a free port and use it
                            NAO_IP,  # parent broker IP
                            PORT)  # parent broker port

# Create a python module
pythonModule = myModule(module_name)

try:
  # Create a proxy to ALMemory
  memoryProxy = ALProxy("ALMemory", NAO_IP, PORT)

  # Subscribe to the event, saying where we want to be called back
  memoryProxy.subscribeToEvent(event_name, module_name, "dataChanged")

  # Let the picture recognition run
  while count > 0:
    time.sleep(5)

  # Unsubscribe
  memoryProxy.unsubscribeToEvent(event_name, module_name)

except RuntimeError, e:
  print e
  exit(1)

print 'end'